name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      
      - name: Test
        run: cat Release.txt
      
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body_path: Release.txt
          files: |
            data/*.sql.gz
            data/*.dat
            data/*.db
            data/*.txt