name: Create Release

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      
      - name: Test
        run: cat Release.txt
      
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            Release.txt
            data/*.db.gz
            data/*.sql.gz
            data/*.dat
            data/*.db
            data/*.txt